version: '3'
services:

  dcache-pool:
    image: dcache/dcache:11.0
    hostname: pool-node-1
    networks:
      - dcache
    volumes:
      - ../common/dcache.conf:/opt/dcache/etc/dcache.conf
      - ./docker-layout.conf:/opt/dcache/etc/layouts/docker-layout.conf
      - ./data:/pool

networks:
  dcache:
    external: true
    name: dcache
