version: '3'
services:

  zk:
    image: zookeeper:3.9
    restart: always
    environment:
      ZOO_ADMINSERVER_ENABLED: "false"
    networks:
      - dcache

  pg:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: chimera
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: let-me-in
    networks:
      - dcache
    volumes: 
      - ./pgdata:/var/lib/postgresql/data

networks:
  dcache:
    name: dcache
