---
apiVersion: v1
kind: Service
metadata:
  name: zk
  namespace: dcache-fuse
spec:
  selector:
    app: zk
  ports:
    - port: 2181
      targetPort: 2181
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zk
  namespace: dcache-fuse
spec:
  serviceName: zk
  replicas: 1
  selector:
    matchLabels:
      app: zk
  template:
    metadata:
      labels:
        app: zk
    spec:
      containers:
        - name: zookeeper
          image: zookeeper:3.9
          ports:
            - containerPort: 2181
          env:
            - name: ZOO_ADMINSERVER_ENABLED
              value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: pg
  namespace: dcache-fuse
spec:
  selector:
    app: pg
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pg
  namespace: dcache-fuse
spec:
  serviceName: pg
  replicas: 1
  selector:
    matchLabels:
      app: pg
  template:
    metadata:
      labels:
        app: pg
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: chimera
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: let-me-in
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: pg-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
